"""create user table

Revision ID: 2bd3a3ccf8be
Revises: 
Create Date: 2022-12-26 15:09:11.462619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd3a3ccf8be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_role_permission',
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.Column('role_permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_account_role_permission_id'), 'account_role_permission', ['id'], unique=False)
    op.create_table('account_user',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('temp_password', sa.String(length=255), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('register_ip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failed_login_attemp', sa.SmallInteger(), nullable=False),
    sa.Column('last_user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_login_ts', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('last_login_loc', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['account_role_permission.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_account_user_id'), 'account_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_id'), table_name='account_user')
    op.drop_table('account_user')
    op.drop_index(op.f('ix_account_role_permission_id'), table_name='account_role_permission')
    op.drop_table('account_role_permission')
    # ### end Alembic commands ###
