"""alter user table

Revision ID: c8e7cd58c9cb
Revises: 2bd3a3ccf8be
Create Date: 2022-12-26 19:51:54.261573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e7cd58c9cb'
down_revision = '2bd3a3ccf8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('access_token', sa.Text(), nullable=True))
    op.drop_column('account_user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('account_user', 'access_token')
    # ### end Alembic commands ###
